### ISSUE TITLE
The link here has nothing in it.

### ISSUE THREAD

**Issue by versamodule** [chegewara/esp32-usb-v2#5]
https://github.com/chegewara/esp32-usb-v2/tree/master/examples/esp-idf

**Comment by chegewara** [comment]
Hi,
yes, it is empty folder, because i wanted to make this library arduino and esp-idf compatible and i failed.
I failed, because arduino-esp32 is using own tinyusb library, which is not compatible with esp-idf component.
At the moment i have no time and lack of desire to continue work on this library.

**Comment by versamodule** [comment]
No problem I understand. Thanks for making what you have done public.
